name: CI

on: 
  push:
    branches: -master

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: .\SelfTestBuild.ps1
      shell: powershell
